# Generated by Django 4.0.6 on 2022-08-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='food_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.ovqatlar'),
        ),
        migrations.AddField(
            model_name='branch',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
