# Generated by Django 4.0.6 on 2022-08-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_addtocart_food_obj_branch_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovqatlar',
            name='paket_narxi',
        ),
    ]
