# Generated by Django 4.0.6 on 2022-09-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_ovqatlar_paket_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='telegram_group_name1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
