# Generated by Django 4.0.6 on 2022-09-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_branch_telegram_group_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='telegram_group_name1',
            new_name='telegraph_link',
        ),
    ]
