# Generated by Django 4.0.6 on 2022-09-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_branch_color_for_statistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.CharField(default='', max_length=100),
        ),
    ]
